version: '3.4'

networks:
  frontend:
  backend:

services:
  bookapi:
    image: ${DOCKER_REGISTRY-}bookapi
    build:
      context: .
      dockerfile: BookAPI/Dockerfile
    environment:
       DatabaseServer: mssqlserver
       DatabaseName: BookDb
       DatabaseUser: sa
       DatabaseUserPassword: BookApi(!)
       ExternalBooksBaseUrl: http://localhost:6001
    container_name: bookapi
    ports:
       - "6001:80"
    networks:
       - backend
       - frontend
    depends_on:
       - mssqlserver

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:6015
    container_name: tokenserviceapi
    ports:
       - "5030:80"
    networks:
       - backend
       - frontend
    depends_on:
       - mssqlserver

  webmvc:
    build:
      context: .
      dockerfile: WebMvc/Dockerfile
    environment:
       ASPNETCORE_ENVIRONMENT: Development
       BookUrl: http://bookapi
       IdentityUrl: http://10.0.0.83:5030
       CallBackUrl: http://localhost:6015
    container_name: bookWebShop
    ports:
       - "6015:80"
    networks:
       - frontend
    depends_on:
       - bookapi
       - tokenserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: BookApi(!)
    ports:
        - "7016:1433"
    networks:
        - backend
